### ISSUE TITLE
与JMessage一起用iOS编译通不过

### ISSUE THREAD

**Issue by hanyou** [wilhantian/cordova-plugin-janalytics#1]
很尴尬的事情。
JMessage.framework带了jcore的静态库，但使用您的JAnalytics又依赖装了一个1.1.1.a，编译时静态库有580个重复，如果直接删除jcore-ios-1.1.1.a，则报找不到引用变量的问题。

**Comment by wilhantian** [comment]
Hi~
关于这个问题暂时没有解决方案，只有手动将jcore库去重。
不过，此插件已经交由Jpush官方维护，jpush、jmessage、janalytics会在后续开发仅依赖一个jcore项目。
你可以在[Jpush官方库](https://github.com/jpush)中找到
